version: "3.1"

services:
  ng:
    container_name: "nginx_inception"
    build: "requirements/nginx/."
    ports:
     - "443:443"
    depends_on:
     - wrdp
     - mariadb
    volumes:
     - wordpress:/var/www/html
    networks:
      net_inception:
  wrdp:
    container_name: "wordpress_inception"
    build: "requirements/wordpress/."
    depends_on:
     - mariadb
    volumes:
     - wordpress:/var/www/html
    networks:
      net_inception:
  mariadb:
    container_name: "mariadb_inception"
    build: "requirements/mariadb/."
    volumes:
     - mariadb:/var/lib/mysql
    networks:
      net_inception:

volumes:
  mariadb:
  wordpress:

networks:
  net_inception:
    driver: bridge