#########################################################################
#                                                                       #
#                                                                       #
#                      Dan Lerma 2024                                   #
#                                                                       #
#                                                                       #
#########################################################################

version: '3'

services:
    mariadb:
        hostname: "INCEPTION-DAN-MARIADB"
        container_name: "INCEPTION-MARIADB"
        build: .
        restart: always
        tty: true
        networks:
            comms:
                ipv4_address: 192.168.156.4
        ports:
            - 3306:3306
        expose:
            - 443
            - 3306
            - 22
            - 80
        volumes:
            - mariadb-volume:/var/lib/docker/mariadb

networks:
    comms:
        driver: bridge
        ipam:
            config:
                - subnet: "192.168.156.0/28"
                  gateway: "192.168.156.1"

volumes:
    mariadb-volume:
        external: false
