#!/bin/bash
FROM debian:buster
#RUN echo 'deb http://deb.debian.org/debian bookworm-backports main' > /etc/apt/sources.list.d/backports.list
#RUN apt-get -y update
#RUN echo "nameserver 8.8.8.8" >> /etc/resolv.conf
RUN echo "Estas dentro de Wordpress" && uname -r

